### ISSUE TITLE
Add the ability to load new images into the application

### ISSUE THREAD

**Issue by jsseng** [jsseng/jigsaw#17]
Have a way to load in a new image as a puzzle.

**Comment by jsseng** [comment]
Have an 'images' directory and load all the images in the directory.  Display them as thumbnails and let the user choose one.

**Comment by vhuang20** [comment]
https://github.com/jsseng/jigsaw/assets/156066664/993415d9-e4c2-4018-9db4-ea8a39440a54

**Comment by KailuanLiu** [comment]
created thumbnails for 3 different puzzles, was able to make it so that when a city name is selected, it leads to the puzzle gameplay. - kai + vincent

**Comment by stephenlin801** [comment]
As part of the UI tweaks I added the ability to select a puzzle of your choice from a grid menu.
![image](https://github.com/jsseng/jigsaw/assets/145500043/275d3d6c-c314-4d94-b516-79416f340c09)

In order to load in new images there is a folder called jigsawpuzzleimages that you simply drag new images in to and the menu will adjust to accommodate the new images accordingly.
